// components/Site/Footer.vue
<script setup lang="ts">
import { FOOTER_LINKS, SOCIAL_LINKS } from "~/constants";
</script>

<template>
  <footer class="py-5 flex flex-col sm:flex-row items-center justify-between gap-y-2">
    <p class="order-last sm:order-first text-neutral-400">
      Made by
      <NuxtLink :to="SOCIAL_LINKS.github" target="_blank" external class="text-peach hover:underline">
        moaqz
      </NuxtLink>
    </p>

    <ul class="flex items-center justify-center flex-wrap gap-x-5 gap-y-2">
      <li v-for="link in FOOTER_LINKS" :key="link.name">
        <NuxtLink
          :to="link.path" :target="link.external ? '_blank' : undefined" :external="link.external"
          class="text-neutral-400 hover:text-peach transition-colors hover:underline"
        >
          {{ link.name }}
        </NuxtLink>
      </li>
    </ul>
  </footer>
</template>

// src/components/footer.tsx
import { SOCIAL_LINKS } from "~/lib/constants";

export default function Footer() {
  return (
    <footer>
      <div className="flex items-center justify-between py-6">
        <p className="text-zinc-300">
          Made by{" "}
          <a
            href={SOCIAL_LINKS.portfolio}
            target="_blank"
            rel="noreferrer"
            className="underline decoration-indigo-500 decoration-wavy"
          >
            moaqz
          </a>{" "}
          using Next.js
        </p>

        <a href={SOCIAL_LINKS.repository} target="_blank" rel="noreferrer">
          <svg
            className="h-6 w-6 text-zinc-300 hover:text-white hover:transition-colors"
            fill="currentColor"
            viewBox="0 0 24 24"
            aria-hidden="true"
          >
            <path
              fillRule="evenodd"
              d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"
              clipRule="evenodd"
            />
          </svg>
          <span className="sr-only">Github</span>
        </a>
      </div>
    </footer>
  );
}
